const t=JSON.parse('{"key":"v-252fbcb1","path":"/Java/basic/3.Exception_Error.html","title":"Exception和Error的区别","lang":"zh-CN","frontmatter":{"order":3,"author":null,"title":"Exception和Error的区别","category":["Java基础","Exception"],"description":"在 Java 中，Exception 和 Error 都是 Throwable 类的子类（只有继承了 Throwable 类的实例才可以被 throw 或者被 catch）。它们表示在程序运行时发生的异常或错误情况。 总结来看：Exception 表示可以被处理的程序异常，Error 表示系统级的不可恢复错误。 详细说明： 1) Exception：表...","head":[["meta",{"property":"og:url","content":"https://tim-qtp.github.io/blog/blog/Java/basic/3.Exception_Error.html"}],["meta",{"property":"og:site_name","content":"Qtp"}],["meta",{"property":"og:title","content":"Exception和Error的区别"}],["meta",{"property":"og:description","content":"在 Java 中，Exception 和 Error 都是 Throwable 类的子类（只有继承了 Throwable 类的实例才可以被 throw 或者被 catch）。它们表示在程序运行时发生的异常或错误情况。 总结来看：Exception 表示可以被处理的程序异常，Error 表示系统级的不可恢复错误。 详细说明： 1) Exception：表..."}],["meta",{"property":"og:type","content":"article"}],["meta",{"property":"og:locale","content":"zh-CN"}],["meta",{"property":"og:updated_time","content":"2025-01-20T17:06:03.000Z"}],["meta",{"property":"article:author","content":"tim-qtp"}],["meta",{"property":"article:modified_time","content":"2025-01-20T17:06:03.000Z"}],["script",{"type":"application/ld+json"},"{\\"@context\\":\\"https://schema.org\\",\\"@type\\":\\"Article\\",\\"headline\\":\\"Exception和Error的区别\\",\\"image\\":[\\"\\"],\\"dateModified\\":\\"2025-01-20T17:06:03.000Z\\",\\"author\\":[{\\"@type\\":\\"Person\\",\\"name\\":\\"tim-qtp\\",\\"url\\":\\"https://github.com/tim-qtp/\\"}]}"]]},"headers":[{"level":3,"title":"2.   logger.error() 做日志保存","slug":"_2-logger-error-做日志保存","link":"#_2-logger-error-做日志保存","children":[]}],"git":{"createdTime":1737392763000,"updatedTime":1737392763000,"contributors":[{"name":"tim-qtp","email":"2469100031@qq.com","commits":1}]},"readingTime":{"minutes":1.86,"words":557},"filePathRelative":"Java/basic/3.Exception&Error.md","localizedDate":"2025年1月20日","autoDesc":true,"excerpt":""}');export{t as data};
